---
Authors: ["**Achal Neupane**"]
title: "Generalized Additive Models and Spline Models"
date: 2019-10-01T17:26:23-05:00
draft: false
output: html_document
tags:
- R
- Statistics
summary: Statistics series
---



<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
<pre class="r"><code>knitr::opts_chunk$set(echo=T, warning=FALSE, message=FALSE)</code></pre>
<p>In statistics, a generalized additive model (GAM) is a generalized linear model in which the linear response variable depends linearly on unknown smooth functions of some predictor variables, and interest focuses on inference about these smooth functions.</p>
<p>GAMs were originally developed by Trevor Hastie and Robert Tibshirani to blend properties of generalized linear models with additive models.</p>
<p>The model relates a univariate response variable, Y, to some predictor variables, x<span class="math inline">\(i\)</span>. An exponential family distribution is specified for Y (for example normal, binomial or Poisson distributions) along with a link function g (for example the identity or log functions) relating the expected value of Y to the predictor variables.</p>
<p>More on this from this wiki article: <a href="https://en.wikipedia.org/wiki/Generalized_additive_model" class="uri">https://en.wikipedia.org/wiki/Generalized_additive_model</a></p>
<p>Here, we will use the body fat data (<span class="math inline">\(\textbf{ bodyfat}\)</span> data from <span class="math inline">\(\textbf{TH.data}\)</span> package) for the analysis. Then we will do the following:</p>
<ol style="list-style-type: lower-alpha">
<li>Explore the data graphically. What variables do you think need to be included for predicting bodyfat? (Hint: Are there correlated predictors).</li>
</ol>
<pre class="r"><code>library(ggplot2)
library(mgcv)
library(mboost)
library(caret)
library(gamclass)
library (TH.data)
data (&quot;bodyfat&quot;)
head(bodyfat)</code></pre>
<pre><code>##    age DEXfat waistcirc hipcirc elbowbreadth kneebreadth anthro3a anthro3b
## 47  57  41.68     100.0   112.0          7.1         9.4     4.42     4.95
## 48  65  43.29      99.5   116.5          6.5         8.9     4.63     5.01
## 49  59  35.41      96.0   108.5          6.2         8.9     4.12     4.74
## 50  58  22.79      72.0    96.5          6.1         9.2     4.03     4.48
## 51  60  36.42      89.5   100.5          7.1        10.0     4.24     4.68
## 52  61  24.13      83.5    97.0          6.5         8.8     3.55     4.06
##    anthro3c anthro4
## 47     4.50    6.13
## 48     4.48    6.37
## 49     4.60    5.82
## 50     3.91    5.66
## 51     4.15    5.91
## 52     3.64    5.14</code></pre>
<pre class="r"><code>NROW(bodyfat) </code></pre>
<pre><code>## [1] 71</code></pre>
<pre class="r"><code>library(DescTools)
names(bodyfat)</code></pre>
<pre><code>##  [1] &quot;age&quot;          &quot;DEXfat&quot;       &quot;waistcirc&quot;    &quot;hipcirc&quot;      &quot;elbowbreadth&quot;
##  [6] &quot;kneebreadth&quot;  &quot;anthro3a&quot;     &quot;anthro3b&quot;     &quot;anthro3c&quot;     &quot;anthro4&quot;</code></pre>
<pre class="r"><code>library(ggplot2)
library(GGally)
library(knitr)

cat(&quot;# 1A&quot;)</code></pre>
<pre><code>## # 1A</code></pre>
<pre class="r"><code># plot the variables to see which variables are correlated
# base plot
pairs(bodyfat, main = &quot;base R: plots showing correlation of variables&quot;)</code></pre>
<p><img src="/post/Generalized_additive_and_spine_models/Generalized_additive_and_spline_models_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<pre class="r"><code>#ggplot
p &lt;- ggpairs(bodyfat)
p + labs(title = &quot;ggplot: plots showing correlation of variables&quot;)</code></pre>
<p><img src="/post/Generalized_additive_and_spine_models/Generalized_additive_and_spline_models_files/figure-html/unnamed-chunk-1-2.png" width="672" /></p>
<pre class="r"><code>cat(&quot;all of the anthros correlate with each other&quot;)</code></pre>
<pre><code>## all of the anthros correlate with each other</code></pre>
<pre class="r"><code>body_f &lt;- glm(DEXfat ~ ., data=bodyfat)
bf_step &lt;- step(body_f, trace = 0)

cat(&quot;step recommends: waistcirc, hipcirc, kneebreadth and anthro3b&quot;)</code></pre>
<pre><code>## step recommends: waistcirc, hipcirc, kneebreadth and anthro3b</code></pre>
<pre class="r"><code>bf_step</code></pre>
<pre><code>## 
## Call:  glm(formula = DEXfat ~ waistcirc + hipcirc + kneebreadth + anthro3b, 
##     data = bodyfat)
## 
## Coefficients:
## (Intercept)    waistcirc      hipcirc  kneebreadth     anthro3b  
##    -71.7197       0.2037       0.3546       1.8047       7.1264  
## 
## Degrees of Freedom: 70 Total (i.e. Null);  66 Residual
## Null Deviance:       8536 
## Residual Deviance: 676.9     AIC: 373.6</code></pre>
<pre class="r"><code>kable(summary(bf_step)$coefficients, caption = &quot;Coefficients from step function&quot;)</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-1">Table 1: </span>Coefficients from step function</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Estimate</th>
<th align="right">Std. Error</th>
<th align="right">t value</th>
<th align="right">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-71.7196776</td>
<td align="right">5.0140437</td>
<td align="right">-14.303760</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">waistcirc</td>
<td align="right">0.2037314</td>
<td align="right">0.0609069</td>
<td align="right">3.344966</td>
<td align="right">0.0013605</td>
</tr>
<tr class="odd">
<td align="left">hipcirc</td>
<td align="right">0.3546222</td>
<td align="right">0.0767978</td>
<td align="right">4.617607</td>
<td align="right">0.0000185</td>
</tr>
<tr class="even">
<td align="left">kneebreadth</td>
<td align="right">1.8047490</td>
<td align="right">0.6611504</td>
<td align="right">2.729710</td>
<td align="right">0.0081187</td>
</tr>
<tr class="odd">
<td align="left">anthro3b</td>
<td align="right">7.1264238</td>
<td align="right">1.1295927</td>
<td align="right">6.308844</td>
<td align="right">0.0000000</td>
</tr>
</tbody>
</table>
<p>From the plot, it appears that the variables age and elbowbreadth don’t correlate with DEXfat.
However, waistcirc, hipcirc, and all four anthro variables appear to correlate with DEXfat. Based on the plot, I would select waistcirc, hipcirc, anthro3a and anthro3c. However, I would also test the model using anthro3b rather than anthro3a to see which yields a better model.
Additionally, stepwise regression using step() function recommended: kneebreadth, waistcirc, hipcirc and anthro3b. This also confirm that the anthro variables are sufficiently correlated to be represented by one variable which in this case is anthro3b.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Fit a generalised additive model assuming normal errors using the following code.</li>
</ol>
<pre><code>bodyfat_gam &lt;- gam(DEXfat~ s(age) + s(waistcirc) + s(hipcirc) + 
              s(elbowbreadth) + s(kneebreadth)+ s(anthro3a) +
              s(anthro3c), data = bodyfat)</code></pre>
<ul>
<li><p>Assess the <span class="math inline">\(\textbf{summary()}\)</span> and <span class="math inline">\(\textbf{plot()}\)</span> of the model (don’t need GGPLOT). Are all covariates informative? Should all covariates be smoothed or should some be included as a linear effect?</p>
<pre><code>- Report GCV, AIC, adj-R$^2$, and the total model degrees of freedom. 

- Use $\textbf{gam.check()}$ function to look at the diagnostic plot. Does it appear that the normality assumption is violated? </code></pre></li>
</ul>
<pre class="r"><code>cat(&quot;# 1B&quot;)</code></pre>
<pre><code>## # 1B</code></pre>
<pre class="r"><code>bodyfat_gam &lt;- gam(DEXfat ~ s(age) + s(waistcirc) + s(hipcirc) +
                     s(elbowbreadth) + s(kneebreadth) + s(anthro3a) + s(anthro3c),      
                   data = bodyfat)

# Assess Summary
summary(bodyfat_gam)</code></pre>
<pre><code>## 
## Family: gaussian 
## Link function: identity 
## 
## Formula:
## DEXfat ~ s(age) + s(waistcirc) + s(hipcirc) + s(elbowbreadth) + 
##     s(kneebreadth) + s(anthro3a) + s(anthro3c)
## 
## Parametric coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  30.7828     0.2847   108.1   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Approximate significance of smooth terms:
##                   edf Ref.df      F  p-value    
## s(age)          1.000  1.000  0.956 0.333043    
## s(waistcirc)    1.000  1.000 10.821 0.001885 ** 
## s(hipcirc)      1.775  2.235  9.917 0.000171 ***
## s(elbowbreadth) 1.000  1.000  0.001 0.972248    
## s(kneebreadth)  8.754  8.960  6.180 8.35e-06 ***
## s(anthro3a)     1.000  1.000 12.966 0.000751 ***
## s(anthro3c)     7.042  8.041  1.798 0.100906    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## R-sq.(adj) =  0.953   Deviance explained = 96.7%
## GCV = 8.4354  Scale est. = 5.7538    n = 71</code></pre>
<pre class="r"><code># Assess plot
cat (&quot;Plot of a generalized additive model for question 1b:&quot;)</code></pre>
<pre><code>## Plot of a generalized additive model for question 1b:</code></pre>
<pre class="r"><code>layout(matrix(1:9, ncol = 3))
plot(bodyfat_gam)

# plot looks like we don&#39;t need to smooth all variables. These appear linear:
# age, waistcirc, elbowbreadth &amp; anthro3a don&#39;t need smoothing


# Question: How do we evaluate a covariate&#39;s &#39;informative&#39;-ness?
# Annwer: Look at the p-values of the covariates.

# Report model attributes
cat(&quot;GCV&quot;)</code></pre>
<pre><code>## GCV</code></pre>
<pre class="r"><code>bodyfat_gam$gcv.ubre            # GCV</code></pre>
<pre><code>##   GCV.Cp 
## 8.435412</code></pre>
<pre class="r"><code>cat(&quot;AIC&quot;)</code></pre>
<pre><code>## AIC</code></pre>
<pre class="r"><code>bodyfat_gam$aic                 # AIC</code></pre>
<pre><code>## [1] 345.708</code></pre>
<pre class="r"><code>cat(&quot;Adjusted R-squared&quot;)</code></pre>
<pre><code>## Adjusted R-squared</code></pre>
<pre class="r"><code>summary(bodyfat_gam)$r.sq       # Adjusted r-squared</code></pre>
<pre><code>## [1] 0.9528156</code></pre>
<pre class="r"><code>cat(&quot;Total degrees of Freedom&quot;)</code></pre>
<pre><code>## Total degrees of Freedom</code></pre>
<pre class="r"><code>sum(bodyfat_gam$edf)            # Total degrees of freedom</code></pre>
<pre><code>## [1] 22.57091</code></pre>
<pre class="r"><code>cat(&quot;Some diagnostics for a fitted gam model using cam.check&quot;)</code></pre>
<pre><code>## Some diagnostics for a fitted gam model using cam.check</code></pre>
<pre class="r"><code>gam.check(bodyfat_gam)  # Response Vs Fitted values</code></pre>
<p><img src="/post/Generalized_additive_and_spine_models/Generalized_additive_and_spline_models_files/figure-html/unnamed-chunk-2-1.png" width="672" /><img src="/post/Generalized_additive_and_spine_models/Generalized_additive_and_spline_models_files/figure-html/unnamed-chunk-2-2.png" width="672" /></p>
<pre><code>## 
## Method: GCV   Optimizer: magic
## Smoothing parameter selection converged after 41 iterations.
## The RMS GCV score gradient at convergence was 2.767255e-07 .
## The Hessian was positive definite.
## Model rank =  64 / 64 
## 
## Basis dimension (k) checking results. Low p-value (k-index&lt;1) may
## indicate that k is too low, especially if edf is close to k&#39;.
## 
##                   k&#39;  edf k-index p-value  
## s(age)          9.00 1.00    0.81   0.025 *
## s(waistcirc)    9.00 1.00    0.94   0.250  
## s(hipcirc)      9.00 1.78    1.02   0.485  
## s(elbowbreadth) 9.00 1.00    0.81   0.030 *
## s(kneebreadth)  9.00 8.75    1.08   0.665  
## s(anthro3a)     9.00 1.00    1.09   0.770  
## s(anthro3c)     9.00 7.04    0.89   0.125  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code># Additionally we can also check for the train() method. Please note that
# train() won&#39;t allow for smoothing the variables; it evidently decides which to
# smooth on its own.
bf_train_gam &lt;- train(DEXfat ~ age +  waistcirc + hipcirc + elbowbreadth + 
                        kneebreadth + anthro3a + anthro3c,      
                      data = bodyfat, method = &quot;gam&quot;)
summary(bf_train_gam)</code></pre>
<pre><code>## 
## Family: gaussian 
## Link function: identity 
## 
## Formula:
## .outcome ~ s(elbowbreadth) + s(kneebreadth) + s(age) + s(hipcirc) + 
##     s(waistcirc) + s(anthro3a) + s(anthro3c)
## 
## Parametric coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  30.7828     0.2968   103.7   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Approximate significance of smooth terms:
##                       edf Ref.df     F  p-value    
## s(elbowbreadth) 3.186e-07      9 0.000   0.8024    
## s(kneebreadth)  7.825e+00      9 6.978 5.34e-07 ***
## s(age)          6.695e-01      9 0.374   0.0271 *  
## s(hipcirc)      1.843e+00      9 3.740  &lt; 2e-16 ***
## s(waistcirc)    7.598e-01      9 2.512 6.01e-07 ***
## s(anthro3a)     6.742e-01      9 1.446 6.74e-06 ***
## s(anthro3c)     5.959e-01      9 0.975 4.74e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## R-sq.(adj) =  0.949   Deviance explained = 95.8%
## GCV = 7.7062  Scale est. = 6.2553    n = 71</code></pre>
<pre class="r"><code># It looks like train() decided to smooth all the variables.
# This resulted in a less effective model.</code></pre>
<p>Not all covariates should be smoothed. Looking at the plot, the covariates that appear linear are: age, elbowbreadth, waistcirc and anthro3a. That leaves anthro3c, kneebreadth and hipcirc to be smoothed.</p>
<p>Report model attributes:
GCV
8.435412
AIC
345.708
Adjusted R-squared
0.9528156
Total degrees of Freedom
22.57091</p>
<p>gam.check:
While the residuals plot appears random, the histogram makes the data appear skewed to the left, so the assumption of normality doesn’t entirely hold.</p>
<p>This summary shows that age, elbowbreadth, and anthro3c are not significant at
the significance level of 0.05. The variables age, waistcirc, elbowbreadth and
anthro3a all have linear relationships as shown in the plots. The model seems
to give a moderate GCV and high AIC which could possibily be adjusted by
variable selection and using smoothing functions on the variables mentioned
above. The adjusted R2 does indicate that the model explains most of the
variance, but as stated previously the model can improve.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li><p>Now remove insignificant variables and remove smoothing for some variables. Report the summary, plot, GCV, AIC, adj-R<span class="math inline">\(^2\)</span>.</p>
<p>bodyfat_gam2 &lt;- gam(DEXfat~ waistcirc + s(hipcirc) +
s(kneebreadth)+ anthro3a +
s(anthro3c), data = bodyfat)</p></li>
</ol>
<pre class="r"><code>cat(&quot;# 1C&quot;)</code></pre>
<pre><code>## # 1C</code></pre>
<pre class="r"><code># Removing insignificant elbowbreadth including age variables
bodyfat_gam2 &lt;- gam(DEXfat ~ waistcirc + s(hipcirc) +
                      s(kneebreadth) + s(anthro3a) + s(anthro3c),      
                    data = bodyfat)
# Assess Summary
summary(bodyfat_gam2)</code></pre>
<pre><code>## 
## Family: gaussian 
## Link function: identity 
## 
## Formula:
## DEXfat ~ waistcirc + s(hipcirc) + s(kneebreadth) + s(anthro3a) + 
##     s(anthro3c)
## 
## Parametric coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 13.60862    4.74887   2.866 0.006052 ** 
## waistcirc    0.19654    0.05425   3.623 0.000676 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Approximate significance of smooth terms:
##                  edf Ref.df      F  p-value    
## s(hipcirc)     1.610  2.010 10.910 0.000115 ***
## s(kneebreadth) 8.793  8.970  6.780 6.07e-06 ***
## s(anthro3a)    1.000  1.000 18.035 9.43e-05 ***
## s(anthro3c)    7.117  8.103  2.126 0.049342 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## R-sq.(adj) =  0.954   Deviance explained = 96.7%
## GCV = 7.9464  Scale est. = 5.6498    n = 71</code></pre>
<pre class="r"><code># wastcirc and anthro3a are no longer the most signifcant parameter.

# Assess plot
cat(&quot;Plots for the model after removing insignificant variables&quot;)</code></pre>
<pre><code>## Plots for the model after removing insignificant variables</code></pre>
<pre class="r"><code>layout(matrix(1:4, ncol = 2))
plot(bodyfat_gam2)</code></pre>
<p><img src="/post/Generalized_additive_and_spine_models/Generalized_additive_and_spline_models_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<pre class="r"><code># plot looks like we don&#39;t need to smooth all variables.  These appear linear:
# anthro3a and (possibly) hipcirc


# Report model attributes
cat(&quot;GCV of bodyfat_gam2&quot;)</code></pre>
<pre><code>## GCV of bodyfat_gam2</code></pre>
<pre class="r"><code>bodyfat_gam2$gcv.ubre            # GCV</code></pre>
<pre><code>##   GCV.Cp 
## 7.946447</code></pre>
<pre class="r"><code>cat(&quot;AIC of bodyfat_gam2&quot;)</code></pre>
<pre><code>## AIC of bodyfat_gam2</code></pre>
<pre class="r"><code>bodyfat_gam2$aic                 # AIC</code></pre>
<pre><code>## [1] 343.2562</code></pre>
<pre class="r"><code>cat(&quot;Adjusted r-squared of bodyfat_gam2&quot;)</code></pre>
<pre><code>## Adjusted r-squared of bodyfat_gam2</code></pre>
<pre class="r"><code>summary(bodyfat_gam2)$r.sq       # Adjusted r-squared</code></pre>
<pre><code>## [1] 0.9536683</code></pre>
<pre class="r"><code>cat(&quot;Total Degrees of freedom of bodyfat_gam2&quot;)</code></pre>
<pre><code>## Total Degrees of freedom of bodyfat_gam2</code></pre>
<pre class="r"><code>sum(bodyfat_gam2$edf)            # Total degrees of freedom</code></pre>
<pre><code>## [1] 20.52</code></pre>
<pre class="r"><code># run gam.check: is the normality assumption violated?
gam.check(bodyfat_gam2)</code></pre>
<p><img src="/post/Generalized_additive_and_spine_models/Generalized_additive_and_spline_models_files/figure-html/unnamed-chunk-3-2.png" width="672" /></p>
<pre><code>## 
## Method: GCV   Optimizer: magic
## Smoothing parameter selection converged after 31 iterations.
## The RMS GCV score gradient at convergence was 7.054782e-07 .
## The Hessian was positive definite.
## Model rank =  38 / 38 
## 
## Basis dimension (k) checking results. Low p-value (k-index&lt;1) may
## indicate that k is too low, especially if edf is close to k&#39;.
## 
##                  k&#39;  edf k-index p-value
## s(hipcirc)     9.00 1.61    1.01    0.44
## s(kneebreadth) 9.00 8.79    1.06    0.70
## s(anthro3a)    9.00 1.00    1.11    0.80
## s(anthro3c)    9.00 7.12    0.91    0.18</code></pre>
<p>GCV of bodyfat_gam2:
7.946447
AIC of bodyfat_gam2:
343.2562
Adjusted r-squared of bodyfat_gam2:
0.9536683
Total Degrees of freedom of bodyfat_gam2:
20.52</p>
<pre><code>d) Again fit an additive model to the body fat data, but this time for a log-transformed response. Compare the three models, which one is more appropriate? (Hint: use Adj-R$^2$, residual plots, etc. to compare models).</code></pre>
<pre class="r"><code>#
cat(&quot;# 1D&quot;)</code></pre>
<pre><code>## # 1D</code></pre>
<pre class="r"><code>#

log_transferred_DEX &lt;- log(bodyfat$DEXfat)
df &lt;- cbind (bodyfat, log_transferred_DEX)

bodyfat_gam3 &lt;- gam(log_transferred_DEX ~ waistcirc + s(hipcirc) +
                      s(kneebreadth) + s(anthro3a) + s(anthro3c),      
                    data = df)
# Assess Summary
summary(bodyfat_gam3)</code></pre>
<pre><code>## 
## Family: gaussian 
## Link function: identity 
## 
## Formula:
## log_transferred_DEX ~ waistcirc + s(hipcirc) + s(kneebreadth) + 
##     s(anthro3a) + s(anthro3c)
## 
## Parametric coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 2.973535   0.158102  18.808   &lt;2e-16 ***
## waistcirc   0.004418   0.001806   2.447   0.0176 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Approximate significance of smooth terms:
##                  edf Ref.df      F  p-value    
## s(hipcirc)     2.909  3.616 11.828  2.1e-06 ***
## s(kneebreadth) 2.325  2.962  2.027 0.128422    
## s(anthro3a)    1.000  1.000 15.576 0.000227 ***
## s(anthro3c)    7.358  8.263  4.678 0.000180 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## R-sq.(adj) =  0.952   Deviance explained = 96.2%
## GCV = 0.0088137  Scale est. = 0.006878  n = 71</code></pre>
<pre class="r"><code># Hipcirc, anthro3a and anthro3c are the most significant smoothed terms and
# Kneebreadth is not significant here. Similarly, waistcirc is barely signifcant
# parameter (&lt;0.005).

# Assess plot
#layout(matrix(1:4, ncol = 2))
#plot(bodyfat_gam3)

# plot looks like we don&#39;t need to smooth all variables.  These appear linear:
# anthro3a.  Hipcirc is prominantly NOT linear in this light.


# Report model attributes
cat(&quot;GCV of bodyfat_gam3&quot;)</code></pre>
<pre><code>## GCV of bodyfat_gam3</code></pre>
<pre class="r"><code>bodyfat_gam3$gcv.ubre            # GCV</code></pre>
<pre><code>##      GCV.Cp 
## 0.008813659</code></pre>
<pre class="r"><code>cat(&quot;AIC of bodyfat_gam3&quot;)</code></pre>
<pre><code>## AIC of bodyfat_gam3</code></pre>
<pre class="r"><code>bodyfat_gam3$aic                 # AIC</code></pre>
<pre><code>## [1] -136.47</code></pre>
<pre class="r"><code>cat(&quot;Adjusted R-square of bodyfat_gam3&quot;)</code></pre>
<pre><code>## Adjusted R-square of bodyfat_gam3</code></pre>
<pre class="r"><code>summary(bodyfat_gam3)$r.sq       # Adjusted r-squared</code></pre>
<pre><code>## [1] 0.9522733</code></pre>
<pre class="r"><code>cat(&quot;Total degrees of freedom of bodyfat_gam3&quot;)</code></pre>
<pre><code>## Total degrees of freedom of bodyfat_gam3</code></pre>
<pre class="r"><code>sum(bodyfat_gam3$edf)            # Total degrees of freedom</code></pre>
<pre><code>## [1] 15.59274</code></pre>
<pre class="r"><code># run gam.check: is the normality assumption violated?
gam.check(bodyfat_gam3)</code></pre>
<p><img src="/post/Generalized_additive_and_spine_models/Generalized_additive_and_spline_models_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre><code>## 
## Method: GCV   Optimizer: magic
## Smoothing parameter selection converged after 11 iterations.
## The RMS GCV score gradient at convergence was 5.573874e-08 .
## The Hessian was positive definite.
## Model rank =  38 / 38 
## 
## Basis dimension (k) checking results. Low p-value (k-index&lt;1) may
## indicate that k is too low, especially if edf is close to k&#39;.
## 
##                  k&#39;  edf k-index p-value  
## s(hipcirc)     9.00 2.91    0.86   0.120  
## s(kneebreadth) 9.00 2.33    0.83   0.055 .
## s(anthro3a)    9.00 1.00    1.00   0.350  
## s(anthro3c)    9.00 7.36    0.99   0.430  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>cat(&quot;Plots for the model with log transferred response&quot;)</code></pre>
<pre><code>## Plots for the model with log transferred response</code></pre>
<pre class="r"><code>par(mfrow=c(1,4))
plot(bodyfat_gam3)</code></pre>
<p><img src="/post/Generalized_additive_and_spine_models/Generalized_additive_and_spline_models_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<p>In this case, the log-transformed model is slightly better in that it accounts for slightly more of the deviation.
Report GCV, AIC, adj-R2, and the total model degrees of freedom.
GCV: 0.0088
AIC: -136.4700
adj-R2: 0.9523
Total DF: 15.5927</p>
<pre><code>e) Fit a generalised additive model that underwent AIC-based variable selection (fitted using function \textbf{             gamboost()} function). What variable was removed by using AIC? 
  \begin{verbatim}
   bodyfat_boost &lt;- gamboost(DEXfat~., data = bodyfat)
   bodyfat_aic &lt;- AIC(bodyfat_boost)
   bf_gam &lt;- bodyfat_boost[mstop(bodyfat_aic)]
  \end{verbatim}</code></pre>
<pre class="r"><code>cat(&quot;# 1E&quot;)</code></pre>
<pre><code>## # 1E</code></pre>
<pre class="r"><code>#

bodyfat_boost &lt;- gamboost(DEXfat ~ ., data=bodyfat)
bodyfat_aic &lt;- AIC(bodyfat_boost)
cat(&quot;printing AIC&quot;)</code></pre>
<pre><code>## printing AIC</code></pre>
<pre class="r"><code>bodyfat_aic</code></pre>
<pre><code>## [1] 3.268173
## Optimal number of boosting iterations: 51 
## Degrees of freedom (for mstop = 51): 7.637287</code></pre>
<pre class="r"><code>bf_gam &lt;- bodyfat_boost[mstop(bodyfat_aic)]

cat(&quot;plots for model fitted using gamboost:&quot;)</code></pre>
<pre><code>## plots for model fitted using gamboost:</code></pre>
<pre class="r"><code>layout(matrix(1:9, ncol = 3))
plot(bf_gam)

cat(&quot;extract variable names&quot;)</code></pre>
<pre><code>## extract variable names</code></pre>
<pre class="r"><code>extract(bf_gam,what=&#39;variable.names&#39;)</code></pre>
<pre><code>##    bbs(waistcirc, df = dfbase)      bbs(hipcirc, df = dfbase) 
##                    &quot;waistcirc&quot;                      &quot;hipcirc&quot; 
## bbs(elbowbreadth, df = dfbase)  bbs(kneebreadth, df = dfbase) 
##                 &quot;elbowbreadth&quot;                  &quot;kneebreadth&quot; 
##     bbs(anthro3a, df = dfbase)     bbs(anthro3b, df = dfbase) 
##                     &quot;anthro3a&quot;                     &quot;anthro3b&quot; 
##     bbs(anthro3c, df = dfbase)      bbs(anthro4, df = dfbase) 
##                     &quot;anthro3c&quot;                      &quot;anthro4&quot;</code></pre>
<pre class="r"><code>cat(&quot;Here, variable &#39;age&#39; was removed&quot;)</code></pre>
<pre><code>## Here, variable &#39;age&#39; was removed</code></pre>
<p><img src="/post/Generalized_additive_and_spine_models/Generalized_additive_and_spline_models_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Age variable was removed by gamboost() function.</p>
<p>Now, we will fit a logistic additive model to the glaucoma data. (Here we will use family = “binomial”). We will examine which covariates should enter the model and how their influence is on the probability of suffering from glaucoma. Since there are many covariates, we may want to use  to fit the GAM model.</p>
<pre class="r"><code>library(&quot;TH.data&quot;)
data(&quot;GlaucomaM&quot;)
# cat(&quot;head(GlaucomaM)&quot;)
# head(GlaucomaM)
# nrow(GlaucomaM) # 196
# names(GlaucomaM)

glau_gamb &lt;- gamboost(Class ~., data = GlaucomaM, family = Binomial())

summary(glau_gamb)</code></pre>
<pre><code>## 
##   Model-based Boosting
## 
## Call:
## gamboost(formula = Class ~ ., data = GlaucomaM, family = Binomial())
## 
## 
##   Negative Binomial Likelihood (logit link) 
## 
## Loss function: { 
##      f &lt;- pmin(abs(f), 36) * sign(f) 
##      p &lt;- exp(f)/(exp(f) + exp(-f)) 
##      y &lt;- (y + 1)/2 
##      -y * log(p) - (1 - y) * log(1 - p) 
##  } 
##  
## 
## Number of boosting iterations: mstop = 100 
## Step size:  0.1 
## Offset:  0 
## Number of baselearners:  62 
## 
## Selection frequencies:
##  bbs(tmi, df = dfbase) bbs(mhcg, df = dfbase) bbs(vars, df = dfbase) 
##                   0.17                   0.11                   0.11 
## bbs(mhci, df = dfbase)  bbs(hvc, df = dfbase) bbs(vass, df = dfbase) 
##                   0.10                   0.08                   0.08 
##   bbs(as, df = dfbase) bbs(vari, df = dfbase)   bbs(mv, df = dfbase) 
##                   0.07                   0.06                   0.04 
## bbs(abrs, df = dfbase) bbs(mhcn, df = dfbase) bbs(phcn, df = dfbase) 
##                   0.03                   0.03                   0.03 
##  bbs(mdn, df = dfbase) bbs(phci, df = dfbase)  bbs(hic, df = dfbase) 
##                   0.03                   0.02                   0.01 
## bbs(phcg, df = dfbase)  bbs(mdi, df = dfbase)  bbs(tms, df = dfbase) 
##                   0.01                   0.01                   0.01</code></pre>
<pre class="r"><code>layout(matrix(1:9, ncol = 3))
plot(glau_gamb)</code></pre>
<p><img src="/post/Generalized_additive_and_spine_models/Generalized_additive_and_spline_models_files/figure-html/unnamed-chunk-6-1.png" width="672" /><img src="/post/Generalized_additive_and_spine_models/Generalized_additive_and_spline_models_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<pre class="r"><code>cat(&quot;Covariates that should enter the model as determined by gamboost:&quot;)</code></pre>
<pre><code>## Covariates that should enter the model as determined by gamboost:</code></pre>
<pre class="r"><code># extract(glau_gamb,what=&#39;variable.names&#39;)
var_names  &lt;- unname(extract(glau_gamb,what=&#39;variable.names&#39;))
var_names</code></pre>
<pre><code>##  [1] &quot;as&quot;   &quot;abrs&quot; &quot;hic&quot;  &quot;mhcg&quot; &quot;mhcn&quot; &quot;mhci&quot; &quot;phcg&quot; &quot;phcn&quot; &quot;phci&quot; &quot;hvc&quot; 
## [11] &quot;vass&quot; &quot;vars&quot; &quot;vari&quot; &quot;mdn&quot;  &quot;mdi&quot;  &quot;tms&quot;  &quot;tmi&quot;  &quot;mv&quot;</code></pre>
<pre class="r"><code>#Using the variables indicated by gamboost, run a gam model to get summary data
# phcg and phci seem smooth already
glau_gam &lt;- gam(Class ~ s(as) + s(abrs)   + s(hic)  + s(mhcg)  + s(mhcn) + s(mhci)             +   phcg +  s(phcn)  + phci + s(hvc) + s(vass) + s(vars) + s(vari) +                   s(mdn) + s(mdi) + s(tms) +  s(tmi) + s(mv), 
                data=GlaucomaM, family=binomial)

summary(glau_gam)</code></pre>
<pre><code>## 
## Family: binomial 
## Link function: logit 
## 
## Formula:
## Class ~ s(as) + s(abrs) + s(hic) + s(mhcg) + s(mhcn) + s(mhci) + 
##     phcg + s(phcn) + phci + s(hvc) + s(vass) + s(vars) + s(vari) + 
##     s(mdn) + s(mdi) + s(tms) + s(tmi) + s(mv)
## 
## Parametric coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)    15.65    1856.24   0.008    0.993
## phcg          602.18   11941.93   0.050    0.960
## phci         -295.39   11160.83  -0.026    0.979
## 
## Approximate significance of smooth terms:
##           edf Ref.df Chi.sq p-value
## s(as)   1.393  1.429  0.006   0.996
## s(abrs) 1.000  1.000  0.001   0.972
## s(hic)  1.000  1.000  0.002   0.966
## s(mhcg) 1.000  1.000  0.001   0.975
## s(mhcn) 1.328  1.356  0.000   0.999
## s(mhci) 2.738  2.815  0.002   1.000
## s(phcn) 3.975  4.024  0.003   1.000
## s(hvc)  5.194  5.266  0.012   1.000
## s(vass) 1.000  1.000  0.014   0.905
## s(vars) 1.000  1.000  0.001   0.970
## s(vari) 3.592  3.680  0.010   1.000
## s(mdn)  1.000  1.000  0.000   0.989
## s(mdi)  1.000  1.000  0.001   0.972
## s(tms)  1.000  1.000  0.000   0.999
## s(tmi)  2.456  2.517  0.010   0.999
## s(mv)   1.000  1.000  0.006   0.938
## 
## R-sq.(adj) =      1   Deviance explained =  100%
## UBRE = -0.66687  Scale est. = 1         n = 196</code></pre>
<p>Discussions:</p>
<p>Covariates indicated by gamboost() were used to generate a gam model. The names are listed in the summary printed above. The summary also shows the probability of their influence (somewhat high) for suffering from glaucoma. I think with 100 percent of the deviance explained, there should be a concern that this model is extremely over-fitting.</p>
<p>Next, we will investigate the use of different types of scatterplot smoothers on the Hubble dataset.</p>
<pre class="r"><code>## GAM model
library(&quot;HSAUR3&quot;)
library(&quot;mgcv&quot;)
library(&quot;GGally&quot;)
library(&quot;mboost&quot;)
library(&quot;rpart&quot;)
library(&quot;wordcloud&quot;)

data(&quot;hubble&quot;, package = &quot;gamair&quot;)
head(hubble)</code></pre>
<pre><code>##     Galaxy    y     x
## 1  NGC0300  133  2.00
## 2  NGC0925  664  9.16
## 3 NGC1326A 1794 16.14
## 4  NGC1365 1594 17.95
## 5  NGC1425 1473 21.88
## 6  NGC2403  278  3.22</code></pre>
<pre class="r"><code>sorted_value&lt;-hubble[order(hubble$x),]
x &lt;- sorted_value$x
y &lt;- sorted_value$y

lowess_value &lt;- lowess(x, y)
plot(y~x, data = sorted_value, xlab = &quot;x&quot;, ylab = &quot;y&quot;,main=&quot;base R: Lowess scatterplot smoother&quot;)
lines(lowess_value, lty = 2)</code></pre>
<p><img src="/post/Generalized_additive_and_spine_models/Generalized_additive_and_spline_models_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>ggplot() + aes(x=x, y=y) + 
  geom_point()+
  geom_line(aes(x = lowess_value$x, y = lowess_value$y)) +
    labs(title = &quot;ggplot: Lowess scatterplot smoother&quot;)</code></pre>
<p><img src="/post/Generalized_additive_and_spine_models/Generalized_additive_and_spline_models_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<pre class="r"><code>plot(y~x, data = sorted_value, xlab = &quot;x&quot;, ylab = &quot;y&quot;,main=&quot;base R: Cubic scatterplot smoother&quot;)
cubic_value = gam(y ~ s(x, bs = &quot;cr&quot;), data = sorted_value)
lines(sorted_value$x, predict(cubic_value), lty=6)</code></pre>
<p><img src="/post/Generalized_additive_and_spine_models/Generalized_additive_and_spline_models_files/figure-html/unnamed-chunk-7-3.png" width="672" /></p>
<pre class="r"><code>ggplot() + aes(x=x, y=y) + 
  geom_point()+
  geom_line(aes(x = sorted_value$x, y = predict(cubic_value))) +
    labs(title = &quot;ggplot: Cubic scatterplot smoother&quot;)</code></pre>
<p><img src="/post/Generalized_additive_and_spine_models/Generalized_additive_and_spline_models_files/figure-html/unnamed-chunk-7-4.png" width="672" /></p>
<pre class="r"><code>summary(cubic_value)</code></pre>
<pre><code>## 
## Family: gaussian 
## Link function: identity 
## 
## Formula:
## y ~ s(x, bs = &quot;cr&quot;)
## 
## Parametric coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   924.38      51.87   17.82 4.27e-14 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Approximate significance of smooth terms:
##        edf Ref.df    F  p-value    
## s(x) 2.148  2.648 26.8 2.35e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## R-sq.(adj) =  0.754   Deviance explained = 77.7%
## GCV =  74317  Scale est. = 64570     n = 24</code></pre>
<pre class="r"><code>plot(y~x, data = sorted_value, xlab = &quot;x&quot;, ylab = &quot;y&quot;,main=&quot;base R: Quadratic model scatterplot smoother&quot;)
lm_value = lm(y~x+I(x^2), data = sorted_value)
lines(sorted_value$x, predict(lm_value))</code></pre>
<p><img src="/post/Generalized_additive_and_spine_models/Generalized_additive_and_spline_models_files/figure-html/unnamed-chunk-7-5.png" width="672" /></p>
<pre class="r"><code>ggplot() + aes(x=x, y=y) + 
  geom_point()+
  geom_line(aes(x = sorted_value$x, y = predict(lm_value))) +
    labs(title = &quot;ggplot: Quadratic scatterplot smoother&quot;)</code></pre>
<p><img src="/post/Generalized_additive_and_spine_models/Generalized_additive_and_spline_models_files/figure-html/unnamed-chunk-7-6.png" width="672" /></p>
<p>Based on our analysis, the three different smoothers line show that quadratic is higher than cubic and lowess, while cubic is higher than lowess. However, we may not be quite sure if it would be logical to say whether the smoother one fits better.</p>
