---
Authors: ["**Achal Neupane**"]
title: "Longitudinal data analysis and mixed models"
date: 2019-10-28T17:26:23-05:00
draft: false
output: html_document
tags:
- R
- Statistics
summary: Statistics series
---



<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
<p>Understanding the overall progression of disease is critical to the timing of therapeutic interventions and design of effective clinical trials. Disease progression can be assessed with longitudinal study designs in which outcomes are measured repeatedly over time and are assessed with respect to risk factors, either measured repeatedly or at baseline. Longitudinal data allows researchers to assess temporal disease aspects, but the analysis is complicated by complex correlation structures, irregularly spaced visits, missing data, and mixtures of time-varying and static covariate effects.</p>
<div id="table-1" class="section level2">
<h2>Table 1</h2>
<p>Summary of methods for analyzing longitudinal study data</p>
<table style="width:100%;">
<colgroup>
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Change score analysis</th>
<th>Repeated measures ANOVA</th>
<th>Multivariate ANOVA (MANOVA)</th>
<th>Generalized estimating equations (GEE)</th>
<th>Mixed effect regression (MER)<a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5633048/table/T1/?report=objectonly#TFN1">a</a></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Description</td>
<td>Analyzes differences between outcomes measured at two time points.</td>
<td>Uses two main factors and an interaction term to assess group differences over time</td>
<td>Repeated responses over time treated as multivariate observations.</td>
<td>Designed for analyzing the regression relationship between covariates and repeated responses.</td>
<td></td>
</tr>
<tr class="even">
<td>GEEs do not allow inference on correlation structure of the repeated responses, but MERs do.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Number of time points</td>
<td>Only 2.</td>
<td>Multiple.</td>
<td>Multiple.</td>
<td>Multiple.</td>
<td>Multiple.</td>
</tr>
<tr class="even">
<td>Irregularly timed data</td>
<td>No.</td>
<td>No.</td>
<td>No.</td>
<td>Yes.</td>
<td>Yes.</td>
</tr>
<tr class="odd">
<td>Time-varying predictors</td>
<td>Not allowed.</td>
<td>Time treated as classification variable.</td>
<td>Time treated as classification variable.</td>
<td>Allowed.</td>
<td>Allowed.</td>
</tr>
<tr class="even">
<td>How correlation between repeated responses modeled</td>
<td>Not applicable.</td>
<td>Assumes outcomes have equal variances and covariances over time.</td>
<td>No specific assumption.</td>
<td>Working models<a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5633048/table/T1/?report=objectonly#TFN2">b</a> that may or may not resemble observed correlations.</td>
<td>Random effects that quantify variation among units and serve to describe cluster-specific trends over time.</td>
</tr>
<tr class="odd">
<td>Missing data</td>
<td>Requires complete data. Analysis based on complete-cases or imputed missing values.<a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5633048/table/T1/?report=objectonly#TFN3">c</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<ol style="list-style-type: decimal">
<li><p>Method yields unbiased parameter estimates and standard errors for (a) complete-case analysis when missingness is MCAR, (b) multiple imputation when missingness is MCAR or MAR.</p></li>
<li><p>Method yields only unbiased parameter estimates for (a) single mean imputation when missingness is MCAR, (b) conditional mean imputation when missingness is MCAR or MAR.</p></li>
<li><p>Method yields biased estimates for (a) complete-case analysis when missingness is MAR, (b) last observation carried forward when missingness is MCAR or MAR, (c) single mean imputation when missingness is MAR.</p></li>
</ol>
<p>| Handles missing data without explicit imputation needed.<br />
GEEs assume missingness is MCAR.<br />
Mixed effects regression assume missingness is MAR. |
| Computation | Group differences of change scores analyzed with one-way ANOVA. | ANOVA implementation in standard software (SAS, SPSS, R). | MANOVA implementation in standard software (SAS, SPSS, R). | Quasi-likelihood methods; PROC GENMOD in SAS. | Likelihood methods; PROC MIXED in SAS. |</p>
<p>Read more on this <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5633048/table/T1/?report=objectonly">here.</a></p>
</div>
<div id="part-1" class="section level2">
<h2>Part 1</h2>
<p>Here we will use the data <code>Beat the Blues</code> from package <code>HSAUR3</code> to construct boxplots and compare the factor variable <span class="math inline">\(\textbf{drug}\)</span>. We will do the same for the <span class="math inline">\(\textbf{length}\)</span> variable and discuss our results.</p>
<pre class="r"><code>library(&quot;gee&quot;)
library(&quot;lme4&quot;)
library(&quot;Matrix&quot;)
library(&quot;multcomp&quot;)
library (HSAUR3)
library(ggplot2)
library(plyr)
library(tidyr)

# Construct boxplots to compare the factor variable \textbf{drug} in an
# analogous way to how we constructed boxplots for the treatment
# variable.
data(&quot;BtheB&quot;)

layout(matrix(1:2, nrow=1))

ylim=range(BtheB[ , grep(&quot;bdi&quot;, names(BtheB))],
           na.rm=TRUE)

yes=subset(BtheB, drug==&quot;Yes&quot;)[ , grep(&quot;bdi&quot;, names(BtheB))]
boxplot(yes, main=&quot;Drugs Used&quot;, ylab=&quot;BDI&quot;,
        xlab=&quot;Time (in Months)&quot;, names=c(0,2,3,5,8), 
        ylim=ylim)

no=subset(BtheB, drug==&quot;No&quot;)[ , grep(&quot;bdi&quot;, names(BtheB))]
boxplot(no, main=&quot;Drugs Not Used&quot;, ylab=&quot;BDI&quot;,
        xlab=&quot;Time (in Months)&quot;, names=c(0,2,3,5,8), 
        ylim=ylim)</code></pre>
<p><img src="/post/Longitudinal_Data_Analysis_and_Mixed_Models/Longitudinal_Data_Analysis_and_Mixed_Models_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<pre class="r"><code>#Repeat for the length variable. Discuss the results.
layout(matrix(1:2, nrow = 1))
lengthlow&lt;-subset(BtheB,length==&quot;&lt;6m&quot;)[,grep(&quot;bdi&quot;,names(BtheB))]
boxplot(lengthlow, main =&quot;Length&lt;6m&quot;, ylab= &quot;BDI&quot;, xlab = &quot;Time (in months)&quot;,names=c(0,2,3,5,8))

lengthhigh&lt;-subset(BtheB,length==&quot;&gt;6m&quot;)[,grep(&quot;bdi&quot;,names(BtheB))]
boxplot(lengthhigh, main =&quot;Length&gt;6m&quot;, ylab= &quot;BDI&quot;, xlab = &quot;Time (in months)&quot;,names=c(0,2,3,5,8))</code></pre>
<p><img src="/post/Longitudinal_Data_Analysis_and_Mixed_Models/Longitudinal_Data_Analysis_and_Mixed_Models_files/figure-html/unnamed-chunk-1-2.png" width="672" />
The plots demonstrate that BDI (median or average) declines at a faster rate if they do not take the medication. The plots also demonstrate that when patients live for less than 6 months, BDI (median or average) declines at a higher pace than when patients survive for more than months.</p>
<p>Next, we will use the <span class="math inline">\(\textit{lm}\)</span> function to fit a model to the Beat the Blues data that assumes that the repeated measurements are independent. Compare the results to those from fitting the random intercept model <span class="math inline">\(\textit{BtheB\_lmer1}\)</span>.</p>
<pre class="r"><code>BtheB$subject=factor(rownames(BtheB))
nobs=nrow(BtheB)
cat(&quot;Let change the data in wide format&quot;)</code></pre>
<pre><code>## Let change the data in wide format</code></pre>
<pre class="r"><code>BtheB_long=reshape(BtheB, idvar = &quot;subject&quot;,
                   varying = c(&quot;bdi.2m&quot;, &quot;bdi.3m&quot;, &quot;bdi.5m&quot;, &quot;bdi.8m&quot;),
                   direction = &quot;long&quot;)
BtheB_long$time=rep(c(2, 3, 5, 8), rep(nobs, 4))


BtheB_lm=lm(bdi ~ bdi.pre + time + treatment + drug + 
              length, data=BtheB_long, na.action=na.omit)

summary(BtheB_lm)</code></pre>
<pre><code>## 
## Call:
## lm(formula = bdi ~ bdi.pre + time + treatment + drug + length, 
##     data = BtheB_long, na.action = na.omit)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -23.6779  -5.4177   0.0151   5.3268  27.2688 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     7.32290    1.72765   4.239 3.08e-05 ***
## bdi.pre         0.57396    0.05497  10.440  &lt; 2e-16 ***
## time           -0.93784    0.23650  -3.965 9.36e-05 ***
## treatmentBtheB -3.32254    1.10069  -3.019  0.00278 ** 
## drugYes        -3.56866    1.14717  -3.111  0.00206 ** 
## length&gt;6m       1.71067    1.11056   1.540  0.12463    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.674 on 274 degrees of freedom
##   (120 observations deleted due to missingness)
## Multiple R-squared:  0.395,  Adjusted R-squared:  0.384 
## F-statistic: 35.78 on 5 and 274 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>BtheB_lmer1=lmer(bdi ~ bdi.pre + time + treatment + drug +
                   length + (1 | subject), data=BtheB_long,
                 REML=FALSE, na.action=na.omit)

cftest(BtheB_lmer1)</code></pre>
<pre><code>## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Fit: lmer(formula = bdi ~ bdi.pre + time + treatment + drug + length + 
##     (1 | subject), data = BtheB_long, REML = FALSE, na.action = na.omit)
## 
## Linear Hypotheses:
##                     Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) == 0     5.59239    2.24244   2.494   0.0126 *  
## bdi.pre == 0         0.63968    0.07789   8.212 2.22e-16 ***
## time == 0           -0.70476    0.14639  -4.814 1.48e-06 ***
## treatmentBtheB == 0 -2.32908    1.67036  -1.394   0.1632    
## drugYes == 0        -2.82495    1.72684  -1.636   0.1019    
## length&gt;6m == 0       0.19708    1.63832   0.120   0.9043    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## (Univariate p values reported)</code></pre>
<pre class="r"><code>cat(&quot;Comparison of lm and lmer&quot;)</code></pre>
<pre><code>## Comparison of lm and lmer</code></pre>
<pre class="r"><code>anova(BtheB_lmer1,BtheB_lm)</code></pre>
<pre><code>## Data: BtheB_long
## Models:
## BtheB_lm: bdi ~ bdi.pre + time + treatment + drug + length
## BtheB_lmer1: bdi ~ bdi.pre + time + treatment + drug + length + (1 | subject)
##             npar    AIC    BIC  logLik deviance Chisq Df Pr(&gt;Chisq)    
## BtheB_lm       7 2012.3 2037.7 -999.15   1998.3                        
## BtheB_lmer1    8 1887.5 1916.6 -935.75   1871.5 126.8  1  &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>cat(&quot;We can plot the residuals from Linear model&quot;)</code></pre>
<pre><code>## We can plot the residuals from Linear model</code></pre>
<pre class="r"><code>plot(BtheB_lm, which=2)</code></pre>
<p><img src="/post/Longitudinal_Data_Analysis_and_Mixed_Models/Longitudinal_Data_Analysis_and_Mixed_Models_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre class="r"><code># Assumptions for Mixed-model

residuals &lt;- function(object, obs) obs-predict(object) 
cat(&quot;We can also plot the residuals from linear mixed-model&quot;)</code></pre>
<pre><code>## We can also plot the residuals from linear mixed-model</code></pre>
<pre class="r"><code>layout(matrix(1:2, ncol = 2))
qint &lt;- ranef(BtheB_lmer1)$subject[[&quot;(Intercept)&quot;]]
qres &lt;- residuals(BtheB_lmer1,BtheB_long$bdi.pre)
qqnorm(qint, ylab = &quot;Estimated random intercepts&quot;,
     xlim = c(-3, 3), ylim = c(-20, 20),
     main = &quot;Random intercepts&quot;)
qqline(qint, col=&quot;red&quot;, lwd=3)
qqnorm(qres, xlim = c(-3, 3), ylim = c(-20, 20),
     ylab = &quot;Estimated residuals&quot;,
     main = &quot;Residuals&quot;)
qqline(qres, col=&quot;red&quot;, lwd=3)</code></pre>
<p><img src="/post/Longitudinal_Data_Analysis_and_Mixed_Models/Longitudinal_Data_Analysis_and_Mixed_Models_files/figure-html/unnamed-chunk-2-2.png" width="672" />
In linear model, Bdi.pre, time, treatmentBtheB, and drugYes are significant, but in the lmer model, only bdi.pre and time are significant. This means that the linear model understates the standard errors because it does not account for the correlation over time or the repeated measures.</p>
<p>In the first output, the linear model shows that there is interation between time and treatment with P &lt; 0.05. However, mixed effect model (lmer) indicates that there is no time and treatment effect because p is 0.09.</p>
<p>Next, we will investigate and discuss whether there is any evidence of an interaction between treatment and time for the Beat the Blues data.</p>
<pre class="r"><code># Investigate and discuss whether there is any evidence of an interaction
# between treatment and time for the Beat the Blues data.

cat(&quot;Testing fitted linear model with lm&quot;)</code></pre>
<pre><code>## Testing fitted linear model with lm</code></pre>
<pre class="r"><code>BtheB_lm2=lm(bdi ~ bdi.pre + time + treatment + drug +
                   length + time*treatment + subject, 
                 data=BtheB_long, REML=FALSE, na.action=na.omit)
summary(BtheB_lm2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = bdi ~ bdi.pre + time + treatment + drug + length + 
##     time * treatment + subject, data = BtheB_long, na.action = na.omit, 
##     REML = FALSE)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -12.142  -2.135   0.000   1.475  18.851 
## 
## Coefficients: (4 not defined because of singularities)
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          29.76770    9.56265   3.113 0.002154 ** 
## bdi.pre              -1.65000    0.70622  -2.336 0.020565 *  
## time                 -0.95949    0.21348  -4.494 1.24e-05 ***
## treatmentBtheB      -19.42712   11.68602  -1.662 0.098158 .  
## drugYes               6.00000    3.53108   1.699 0.091000 .  
## length&gt;6m            22.48102   12.10631   1.857 0.064941 .  
## subject10             3.10000    4.52199   0.686 0.493881    
## subject11            19.06898    4.40270   4.331 2.45e-05 ***
## subject12           100.14125   35.32423   2.835 0.005105 ** 
## subject13            18.05000    5.42455   3.327 0.001061 ** 
## subject14            23.31898    5.41836   4.304 2.75e-05 ***
## subject15            15.80000    6.07510   2.601 0.010070 *  
## subject16             5.45000    4.11791   1.323 0.187343    
## subject17            46.96818   12.31014   3.815 0.000186 ***
## subject18            19.78102   12.16794   1.626 0.105760    
## subject19            42.11898    7.12772   5.909 1.67e-08 ***
## subject2             34.65000   11.83833   2.927 0.003862 ** 
## subject20            52.83102   25.34385   2.085 0.038512 *  
## subject21             8.46022    7.50845   1.127 0.261336    
## subject22            33.95000    9.83645   3.451 0.000694 ***
## subject23            14.00000    4.99370   2.804 0.005606 ** 
## subject24             3.67026    8.82128   0.416 0.677853    
## subject25            27.12026    6.73771   4.025 8.36e-05 ***
## subject26            11.81818    5.55378   2.128 0.034694 *  
## subject27             0.95128    6.84960   0.139 0.889699    
## subject28            62.16624   12.24689   5.076 9.51e-07 ***
## subject29            24.00000   14.55901   1.648 0.100992    
## subject3             27.40128    9.26385   2.958 0.003511 ** 
## subject30            12.58102   10.30362   1.221 0.223663    
## subject31            28.60000   10.49865   2.724 0.007078 ** 
## subject32            29.28102   15.42181   1.899 0.059198 .  
## subject33            10.23102    9.57607   1.068 0.286765    
## subject34             1.19125    8.26315   0.144 0.885531    
## subject35            56.95000   20.08684   2.835 0.005101 ** 
## subject36            72.85128   18.52482   3.933 0.000120 ***
## subject37            19.95000    6.66242   2.994 0.003135 ** 
## subject38            13.91898    5.59943   2.486 0.013833 *  
## subject39             3.29920    8.84068   0.373 0.709448    
## subject4             16.25000    6.11601   2.657 0.008590 ** 
## subject40            32.76898    7.02198   4.667 5.94e-06 ***
## subject41           100.19125   33.25146   3.013 0.002956 ** 
## subject42            26.05000    6.07510   4.288 2.93e-05 ***
## subject43           -18.13102   11.53675  -1.572 0.117793    
## subject44            17.51022    6.19857   2.825 0.005261 ** 
## subject45            38.15000   18.69805   2.040 0.042771 *  
## subject46            69.79125   23.95835   2.913 0.004031 ** 
## subject47            61.53102   23.96835   2.567 0.011061 *  
## subject48            10.84579   11.62898   0.933 0.352242    
## subject49            -7.40875    7.23325  -1.024 0.307078    
## subject5             27.71022    9.01742   3.073 0.002447 ** 
## subject50            55.96898    6.58205   8.503 6.75e-15 ***
## subject51            59.90128   16.51807   3.626 0.000374 ***
## subject52            48.24125   19.27469   2.503 0.013206 *  
## subject53            43.46898    4.56947   9.513  &lt; 2e-16 ***
## subject54             3.64920    8.34740   0.437 0.662512    
## subject55            28.08102    7.50271   3.743 0.000244 ***
## subject56             0.63102    7.46940   0.084 0.932767    
## subject57             9.23102    4.40270   2.097 0.037412 *  
## subject58            73.13102   19.55676   3.739 0.000247 ***
## subject59            52.24125   17.72452   2.947 0.003627 ** 
## subject6             -3.36898    7.46940  -0.451 0.652502    
## subject60            -6.08978    5.33361  -1.142 0.255056    
## subject61             7.36898    6.58205   1.120 0.264386    
## subject62            10.01898    6.06957   1.651 0.100536    
## subject63             9.18060    4.07475   2.253 0.025457 *  
## subject64           -19.51709   15.51635  -1.258 0.210070    
## subject65             5.61022    5.42631   1.034 0.302566    
## subject66           -34.50043   16.19268  -2.131 0.034471 *  
## subject67            -0.15000    4.78979  -0.031 0.975052    
## subject68            55.89920   24.10162   2.319 0.021495 *  
## subject69            36.70128   11.36703   3.229 0.001476 ** 
## subject7              2.60000    4.78979   0.543 0.587920    
## subject70            64.84125   21.93711   2.956 0.003534 ** 
## subject71            10.18102    9.70541   1.049 0.295574    
## subject72            54.96818   19.13108   2.873 0.004549 ** 
## subject73           -24.20000   13.65756  -1.772 0.078092 .  
## subject74            -4.99872    6.27981  -0.796 0.427075    
## subject75            -3.33102   11.44996  -0.291 0.771446    
## subject76            23.80000    9.18080   2.592 0.010310 *  
## subject77             4.85000    3.23629   1.499 0.135711    
## subject78             6.90000    5.51572   1.251 0.212560    
## subject79            19.10128    9.01832   2.118 0.035536 *  
## subject8              3.31898    7.69955   0.431 0.666937    
## subject80             9.46898    7.12772   1.328 0.185695    
## subject81            20.36898    4.56947   4.458 1.45e-05 ***
## subject82            -0.08978    5.78228  -0.016 0.987630    
## subject83           -18.18102   14.10427  -1.289 0.199028    
## subject84             8.95000    6.07510   1.473 0.142427    
## subject85            82.36818   21.62732   3.809 0.000191 ***
## subject86            40.75000   16.18143   2.518 0.012659 *  
## subject87            16.76022    7.47517   2.242 0.026168 *  
## subject88             5.56898    5.86055   0.950 0.343253    
## subject89            50.53102   23.96835   2.108 0.036387 *  
## subject9             29.28102   13.89048   2.108 0.036408 *  
## subject90            30.93102   16.08662   1.923 0.056078 .  
## subject92            60.94920   22.05961   2.763 0.006320 ** 
## subject93            21.76246   13.32765   1.633 0.104232    
## subject94             3.20000    4.94351   0.647 0.518249    
## subject95                  NA         NA      NA       NA    
## subject96                  NA         NA      NA       NA    
## subject98                  NA         NA      NA       NA    
## subject99                  NA         NA      NA       NA    
## time:treatmentBtheB   0.64358    0.29757   2.163 0.031867 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.994 on 181 degrees of freedom
##   (120 observations deleted due to missingness)
## Multiple R-squared:  0.8675, Adjusted R-squared:  0.7958 
## F-statistic:  12.1 on 98 and 181 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>cat(&quot;Testing fitted linear mixed-model with lmer subject as a random effect&quot;)</code></pre>
<pre><code>## Testing fitted linear mixed-model with lmer subject as a random effect</code></pre>
<pre class="r"><code>BtheB_lmer2=lmer(bdi ~ bdi.pre + time + treatment + drug +
                   length + time*treatment + (1 | subject), 
                 data=BtheB_long, REML=FALSE, na.action=na.omit)

cftest(BtheB_lmer2)</code></pre>
<pre><code>## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Fit: lmer(formula = bdi ~ bdi.pre + time + treatment + drug + length + 
##     time * treatment + (1 | subject), data = BtheB_long, REML = FALSE, 
##     na.action = na.omit)
## 
## Linear Hypotheses:
##                          Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) == 0          6.47824    2.31905   2.793  0.00521 ** 
## bdi.pre == 0              0.64046    0.07843   8.166 2.22e-16 ***
## time == 0                -0.95555    0.20831  -4.587 4.49e-06 ***
## treatmentBtheB == 0      -4.09804    1.98490  -2.065  0.03896 *  
## drugYes == 0             -2.79209    1.73986  -1.605  0.10854    
## length&gt;6m == 0            0.21905    1.65043   0.133  0.89441    
## time:treatmentBtheB == 0  0.49000    0.28959   1.692  0.09064 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## (Univariate p values reported)</code></pre>
<p>Now, we will create a plot of the mean profiles of both treatment groups in the Beat the Blues data, showing also standard deviation bars at each time point.</p>
<pre class="r"><code># Create a plot of the mean profiles of both treatment groups in the Beat
# the Blues data, showing also standard deviation bars at each time point.
data_sum=ddply(BtheB_long, c(&quot;time&quot;, &quot;treatment&quot;), summarise, 
            N=sum(!is.na(bdi)),
            mean=mean(bdi, na.rm=TRUE),
            sd=sd(bdi, na.rm=TRUE),
            se=sd/sqrt(N))

pd &lt;- position_dodge(0.1)

ggplot(data_sum, aes(x=time, y=mean, colour=treatment)) +
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=0.1, position=pd) +
  geom_line(position=pd) +
  geom_point(position=pd) + 
  theme_classic() +
  labs(title = &quot;Mean profiles of both treatment groups&quot;)</code></pre>
<p><img src="/post/Longitudinal_Data_Analysis_and_Mixed_Models/Longitudinal_Data_Analysis_and_Mixed_Models_files/figure-html/unnamed-chunk-4-1.png" width="672" />
The mean profile shows that the results are very different between the two categories, but the standard deviation bars converge.</p>
<p>Now, consider the <span class="math inline">\(\textbf{phosphate}\)</span> data from the package <code>HSAUR3</code>. This data shows the plasma inorganic phosphate levels for 33 subjects, 20 of whom are controls and 13 of whom have been classified as obese (Davis, 2002). First, we will create boxplots by group and discuss the results below.</p>
<pre class="r"><code>data(&quot;phosphate&quot;, package = &quot;HSAUR3&quot;)
library(lme4)
library(Matrix)
library(multcomp)
attach(phosphate)
par(mfrow = c(1,2))
ylim &lt;-range(phosphate[,-1], na.rm = TRUE)
# Construct boxplots by group and discuss. 
boxplot(phosphate[group == &quot;control&quot;, -1], 
        xlab = &quot;time&quot;, ylab = &quot;Phosphate level&quot;,
        main = &quot;base R: Control group&quot;, ylim = ylim)
boxplot(phosphate[group == &quot;obese&quot;,-1],
        xlab = &quot;time&quot;, ylab = &quot;Phosphate level&quot;,
        main = &quot;Obese group&quot;, ylim = ylim)</code></pre>
<p><img src="/post/Longitudinal_Data_Analysis_and_Mixed_Models/Longitudinal_Data_Analysis_and_Mixed_Models_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code># ggplot version:
phosphate %&gt;%
  gather(time,phosphate_level, 2:9) %&gt;%
  mutate(time = factor(gsub(time,pattern=&quot;[[:alpha:]]&quot;,replacement=&#39;&#39;))) %&gt;%
ggplot(aes(x=time,y=phosphate_level)) +
  geom_boxplot() +
  facet_grid(.~group) +
  labs(title=&#39;ggplot: Phosphate Data by Groups&#39;,
       x=&#39;Time (hours)&#39;,
       y=&#39;Phosphate level&#39;) +
  theme_classic()</code></pre>
<p><img src="/post/Longitudinal_Data_Analysis_and_Mixed_Models/Longitudinal_Data_Analysis_and_Mixed_Models_files/figure-html/unnamed-chunk-5-2.png" width="672" />
Based on the plot, the control group has the median level of phosphate falling rapidly from a higher level of 4.3 to midway between t1 and t2 and starts to rise more rapidly over time. The obese group reached a relatively higher median phosphate rate close to 5 and dropped and grew steadily over time. The Obese group also has two outliers.</p>
<p>Next, we will create separate plots of the profiles of the individuals in each group.</p>
<pre class="r"><code># Produce separate plots of the profiles of the individuals in each group
layout(matrix(1:2, nrow=1))

rg=range(phosphate[ ,-1])
plot(c(1, 8), c(rg), type=&quot;n&quot;, xlab=&quot;Time (hours)&quot;, 
     ylab=&quot;Phosphate Levels&quot;, main=&quot;base R: Control Group&quot;)
for(i in 1:sum(phosphate$group==&quot;control&quot;)){
  lines(1:8, phosphate[i, -1])
}

plot(c(1, 8), c(rg), type=&quot;n&quot;, xlab=&quot;Time (hours)&quot;, 
     ylab=&quot;Phosphate Levels&quot;, main=&quot;Obese Group&quot;)
for(i in 1:sum(phosphate$group==&quot;obese&quot;)){
  lines(1:8, phosphate[nrow(phosphate)-i, -1])
}</code></pre>
<p><img src="/post/Longitudinal_Data_Analysis_and_Mixed_Models/Longitudinal_Data_Analysis_and_Mixed_Models_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>phosphate_t &lt;- phosphate
phosphate_t$subject &lt;- factor(rownames(phosphate_t))

phosphate_t %&gt;%
  gather(time,phosphate_level, 2:9) %&gt;%
  mutate(time = factor(gsub(time,pattern=&quot;[[:alpha:]]&quot;,replacement=&#39;&#39;))) %&gt;%
ggplot(aes(x=time,y=phosphate_level)) +
  geom_line(aes(group=subject,color=subject),size=1) +
  facet_grid(.~group) +
  labs(title=&#39;ggplot: Phosphate by group&#39;,
       x=&#39;Time (in hours)&#39;,
       y=&#39;Phosphate Level&#39;) +
  theme_classic()</code></pre>
<p><img src="/post/Longitudinal_Data_Analysis_and_Mixed_Models/Longitudinal_Data_Analysis_and_Mixed_Models_files/figure-html/unnamed-chunk-6-2.png" width="672" />
Guided by how these plots fit, we may be interested to find out which linear mixed effects models might be sensible based on the intercept and slope, intercept and interaction.</p>
<p>Here, linear mixed model would be suitable because the slopes and intercepts in each group vary widely. Additionally, there is an interaction between control and obese groups based on time. So fitting something of the form <span class="math inline">\(\textit{lmer(phosphatelevel t0+time∗group+(1= phos)}\)</span> would be suitable.</p>
<p>In the fixed effect model, we see that there is a positive relation between the time and the phosphate level. It makes sense sinse we saw that after decreasing for a while the phosphate level increases for longer than decreasing time period. Based on the f-test with cftest , time, group, baseline phosphate level and the interaction between time and group all are significant.</p>
<p>Next, we will convert the data to long version and fit the model of your choice and discuss the results.</p>
<pre class="r"><code># Convert the data to long version and fit the model 
data(phosphate)
ph=phosphate
ph$subject=as.factor(rownames(ph))
##LOng form
a=ph[,c(3:9)]

ph_long=reshape(ph,idvar=&quot;subject&quot;,v.names=&quot;p_level&quot;,
                varying=list(names(a)),direction=&quot;long&quot;)

timer=seq(1:7)
timer[1]=0.5
timer[2]=1
timer[3]=1.5
for(i in 4:7){
  timer[i]=i-2}

for(i in 1:7){
  for(j in 1:33){
    ph_long[(33*(i-1)+j),4]=timer[i]
  }
}

ph_non_inter=lmer(p_level~time+group+t0+(1|subject),data=ph_long,
                  REML=FALSE,na.actio=na.omit)

ph_inter=lmer(p_level~time+group+t0+time*group+(1|subject),
              data=ph_long,REML=FALSE,na.actio=na.omit)

ph_cept_slope=lmer(p_level~time+group+t0+
                     (time|subject),
              data=ph_long,REML=FALSE,na.actio=na.omit)

ph_cept_slope_inter=lmer(p_level~time+group+t0+time*group+
                           (time|subject),
                         data=ph_long,REML=FALSE,na.actio=na.omit)

print(summary(ph_cept_slope_inter))</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood  [&#39;lmerMod&#39;]
## Formula: p_level ~ time + group + t0 + time * group + (time | subject)
##    Data: ph_long
## 
##      AIC      BIC   logLik deviance df.resid 
##    391.4    422.4   -186.7    373.4      222 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.4110 -0.5834 -0.0418  0.5864  3.5255 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr
##  subject  (Intercept) 0.00921  0.09597      
##           time        0.00451  0.06716  1.00
##  Residual             0.25005  0.50005      
## Number of obs: 231, groups:  subject, 33
## 
## Fixed effects:
##                  Estimate Std. Error t value
## (Intercept)      0.001784   0.339776   0.005
## time             0.174229   0.031569   5.519
## groupobese       0.636605   0.137837   4.619
## t0               0.691587   0.079428   8.707
## time:groupobese -0.211030   0.050297  -4.196
## 
## Correlation of Fixed Effects:
##             (Intr) time   gropbs t0    
## time        -0.145                     
## groupobese   0.149  0.356              
## t0          -0.970  0.000 -0.304       
## time:gropbs  0.091 -0.628 -0.568  0.000</code></pre>
<pre class="r"><code>print(cftest(ph_cept_slope_inter))</code></pre>
<pre><code>## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Fit: lmer(formula = p_level ~ time + group + t0 + time * group + (time | 
##     subject), data = ph_long, REML = FALSE, na.action = na.omit)
## 
## Linear Hypotheses:
##                       Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) == 0      0.001784   0.339776   0.005    0.996    
## time == 0             0.174229   0.031569   5.519 3.41e-08 ***
## groupobese == 0       0.636605   0.137837   4.619 3.86e-06 ***
## t0 == 0               0.691587   0.079428   8.707  &lt; 2e-16 ***
## time:groupobese == 0 -0.211030   0.050297  -4.196 2.72e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## (Univariate p values reported)</code></pre>
<pre class="r"><code>anova(ph_inter,ph_non_inter,ph_cept_slope,ph_cept_slope_inter)</code></pre>
<pre><code>## Data: ph_long
## Models:
## ph_non_inter: p_level ~ time + group + t0 + (1 | subject)
## ph_inter: p_level ~ time + group + t0 + time * group + (1 | subject)
## ph_cept_slope: p_level ~ time + group + t0 + (time | subject)
## ph_cept_slope_inter: p_level ~ time + group + t0 + time * group + (time | subject)
##                     npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)
## ph_non_inter           6 411.77 432.43 -199.89   399.77                     
## ph_inter               7 393.19 417.29 -189.59   379.19 20.585  1  5.705e-06
## ph_cept_slope          8 404.23 431.76 -194.11   388.23  0.000  1  1.0000000
## ph_cept_slope_inter    9 391.45 422.43 -186.72   373.45 14.776  1  0.0001211
##                        
## ph_non_inter           
## ph_inter            ***
## ph_cept_slope          
## ph_cept_slope_inter ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>pred=predict(ph_cept_slope_inter)
MSE=mean((pred-ph_long$p_level)^2)
message(&quot;Mean Squared Error: &quot;,MSE)
message(&quot;Mean Phosphate Level: &quot;,mean(ph_long$p_level))</code></pre>
<p>Comparing this with three other models, (ph_non_inter=random intercept, ph_inter=random intercept with interaction, ph_cept_slope=random intercept and random slope) using anova, the model used here has the smallest AIC (about 391) indicating a better fit of among four models. However, considering BIC value, we also see that random intercept with interaction is also a good model.</p>
</div>
<div id="part-2" class="section level2">
<h2>Part 2</h2>
<p>Now, consider the <span class="math inline">\(\textbf{respiratory}\)</span> data from the <span class="math inline">\(\textbf{HSAUR3}\)</span> package. Then, investigate the use of other correlational structures than the independence and exchangeable structures used in the text for the respiratory data.</p>
<pre class="r"><code>library(HSAUR3)
library(gee)
library(geepack)
library(lme4)
library(MuMIn)
library(multcomp)

cat(&quot;1a&quot;)</code></pre>
<pre><code>## 1a</code></pre>
<pre class="r"><code>data(&quot;respiratory&quot;, package=&quot;HSAUR3&quot;)
head(respiratory)</code></pre>
<pre><code>##     centre treatment gender age status month subject
## 1        1   placebo female  46   poor     0       1
## 112      1   placebo female  46   poor     1       1
## 223      1   placebo female  46   poor     2       1
## 334      1   placebo female  46   poor     3       1
## 445      1   placebo female  46   poor     4       1
## 2        1   placebo female  28   poor     0       2</code></pre>
<pre class="r"><code>dim(respiratory)</code></pre>
<pre><code>## [1] 555   7</code></pre>
<pre class="r"><code>resp_sub &lt;- subset(respiratory, month &gt; &quot;0&quot;)
resp_sub$baseline &lt;- rep(subset(respiratory, month == &quot;0&quot;)$status,rep(4, 111))

resp_sub$nstat &lt;- as.numeric(resp_sub$status == &quot;good&quot;)
resp_sub$month &lt;- resp_sub$month[, drop = TRUE]
head(resp_sub, n = 3)</code></pre>
<pre><code>##     centre treatment gender age status month subject baseline nstat
## 112      1   placebo female  46   poor     1       1     poor     0
## 223      1   placebo female  46   poor     2       1     poor     0
## 334      1   placebo female  46   poor     3       1     poor     0</code></pre>
<pre class="r"><code>names(resp_sub)[names(resp_sub) == &quot;treatment&quot;] &lt;- &quot;trt&quot;
levels(resp_sub$trt)[2] &lt;- &quot;trt&quot;

cat(&quot;Now, fitting the models&quot;)</code></pre>
<pre><code>## Now, fitting the models</code></pre>
<pre class="r"><code>resp_sub_glm &lt;- glm(status ~ centre + trt + gender + baseline + age, data = resp_sub, family = &quot;binomial&quot;)

resp_sub_gee1 &lt;- gee(nstat ~ centre + trt+ gender + baseline + age, data = resp_sub, family = &quot;binomial&quot;, id = subject, corstr = &quot;independence&quot;, scale.fix = TRUE, scale.value = 1)</code></pre>
<pre><code>##  (Intercept)      centre2       trttrt   gendermale baselinegood          age 
##  -0.90017133   0.67160098   1.29921589   0.11924365   1.88202860  -0.01816588</code></pre>
<pre class="r"><code>resp_sub_gee2 &lt;- gee(nstat ~ centre + trt + gender + baseline + age, data =resp_sub, family = &quot;binomial&quot;, id = subject, corstr = &quot;exchangeable&quot;, scale.fix = TRUE, scale.value = 1)</code></pre>
<pre><code>##  (Intercept)      centre2       trttrt   gendermale baselinegood          age 
##  -0.90017133   0.67160098   1.29921589   0.11924365   1.88202860  -0.01816588</code></pre>
<pre class="r"><code>resp_sub_gee3 &lt;- gee(nstat ~ centre + trt + gender + baseline + age, data =resp_sub, family = &quot;binomial&quot;, id = subject, corstr = &quot;unstructured&quot;, scale.fix = TRUE, scale.value = 1)</code></pre>
<pre><code>##  (Intercept)      centre2       trttrt   gendermale baselinegood          age 
##  -0.90017133   0.67160098   1.29921589   0.11924365   1.88202860  -0.01816588</code></pre>
<pre class="r"><code>resp_sub_gee4 &lt;- gee(nstat ~ centre + trt + gender + baseline + age, data =resp_sub, family = &quot;binomial&quot;, id = subject, corstr = &quot;AR-M&quot;, scale.fix = TRUE, scale.value = 1)</code></pre>
<pre><code>##  (Intercept)      centre2       trttrt   gendermale baselinegood          age 
##  -0.90017133   0.67160098   1.29921589   0.11924365   1.88202860  -0.01816588</code></pre>
<pre class="r"><code>cat(&quot; Summary&quot;)</code></pre>
<pre><code>##  Summary</code></pre>
<pre class="r"><code>knitr::kable(summary(resp_sub_glm)$coeff, caption = &quot;Summary coeff of GLM binomial&quot;)</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-8">Table 1: </span>Summary coeff of GLM binomial</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Estimate</th>
<th align="right">Std. Error</th>
<th align="right">z value</th>
<th align="right">Pr(&gt;|z|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-0.9001713</td>
<td align="right">0.3376530</td>
<td align="right">-2.6659658</td>
<td align="right">0.0076767</td>
</tr>
<tr class="even">
<td align="left">centre2</td>
<td align="right">0.6716010</td>
<td align="right">0.2395666</td>
<td align="right">2.8034004</td>
<td align="right">0.0050567</td>
</tr>
<tr class="odd">
<td align="left">trttrt</td>
<td align="right">1.2992159</td>
<td align="right">0.2368410</td>
<td align="right">5.4856047</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">gendermale</td>
<td align="right">0.1192436</td>
<td align="right">0.2946710</td>
<td align="right">0.4046671</td>
<td align="right">0.6857223</td>
</tr>
<tr class="odd">
<td align="left">baselinegood</td>
<td align="right">1.8820286</td>
<td align="right">0.2412902</td>
<td align="right">7.7998563</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">age</td>
<td align="right">-0.0181659</td>
<td align="right">0.0088644</td>
<td align="right">-2.0493065</td>
<td align="right">0.0404322</td>
</tr>
</tbody>
</table>
<pre class="r"><code>knitr::kable(summary(resp_sub_gee1)$coef, caption = &quot;Summary coeff of GEE binomial independent&quot;)</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-8">Table 1: </span>Summary coeff of GEE binomial independent</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Estimate</th>
<th align="right">Naive S.E.</th>
<th align="right">Naive z</th>
<th align="right">Robust S.E.</th>
<th align="right">Robust z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-0.9001713</td>
<td align="right">0.3376531</td>
<td align="right">-2.665965</td>
<td align="right">0.4603270</td>
<td align="right">-1.9555041</td>
</tr>
<tr class="even">
<td align="left">centre2</td>
<td align="right">0.6716010</td>
<td align="right">0.2395666</td>
<td align="right">2.803400</td>
<td align="right">0.3568191</td>
<td align="right">1.8821889</td>
</tr>
<tr class="odd">
<td align="left">trttrt</td>
<td align="right">1.2992159</td>
<td align="right">0.2368410</td>
<td align="right">5.485603</td>
<td align="right">0.3507780</td>
<td align="right">3.7038127</td>
</tr>
<tr class="even">
<td align="left">gendermale</td>
<td align="right">0.1192436</td>
<td align="right">0.2946710</td>
<td align="right">0.404667</td>
<td align="right">0.4432023</td>
<td align="right">0.2690501</td>
</tr>
<tr class="odd">
<td align="left">baselinegood</td>
<td align="right">1.8820286</td>
<td align="right">0.2412902</td>
<td align="right">7.799855</td>
<td align="right">0.3500515</td>
<td align="right">5.3764332</td>
</tr>
<tr class="even">
<td align="left">age</td>
<td align="right">-0.0181659</td>
<td align="right">0.0088644</td>
<td align="right">-2.049306</td>
<td align="right">0.0130043</td>
<td align="right">-1.3969169</td>
</tr>
</tbody>
</table>
<pre class="r"><code>knitr::kable(summary(resp_sub_gee2)$coef, caption = &quot;Summary coeff of GEE binomial exchangeable&quot;)</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-8">Table 1: </span>Summary coeff of GEE binomial exchangeable</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Estimate</th>
<th align="right">Naive S.E.</th>
<th align="right">Naive z</th>
<th align="right">Robust S.E.</th>
<th align="right">Robust z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-0.9001713</td>
<td align="right">0.4784634</td>
<td align="right">-1.8813796</td>
<td align="right">0.4603270</td>
<td align="right">-1.9555041</td>
</tr>
<tr class="even">
<td align="left">centre2</td>
<td align="right">0.6716010</td>
<td align="right">0.3394723</td>
<td align="right">1.9783676</td>
<td align="right">0.3568191</td>
<td align="right">1.8821889</td>
</tr>
<tr class="odd">
<td align="left">trttrt</td>
<td align="right">1.2992159</td>
<td align="right">0.3356101</td>
<td align="right">3.8712064</td>
<td align="right">0.3507780</td>
<td align="right">3.7038127</td>
</tr>
<tr class="even">
<td align="left">gendermale</td>
<td align="right">0.1192436</td>
<td align="right">0.4175568</td>
<td align="right">0.2855747</td>
<td align="right">0.4432023</td>
<td align="right">0.2690501</td>
</tr>
<tr class="odd">
<td align="left">baselinegood</td>
<td align="right">1.8820286</td>
<td align="right">0.3419147</td>
<td align="right">5.5043802</td>
<td align="right">0.3500515</td>
<td align="right">5.3764332</td>
</tr>
<tr class="even">
<td align="left">age</td>
<td align="right">-0.0181659</td>
<td align="right">0.0125611</td>
<td align="right">-1.4462014</td>
<td align="right">0.0130043</td>
<td align="right">-1.3969169</td>
</tr>
</tbody>
</table>
<pre class="r"><code>knitr::kable(summary(resp_sub_gee3)$coef, caption = &quot;Summary coeff of GEE binomial unstructured&quot;)</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-8">Table 1: </span>Summary coeff of GEE binomial unstructured</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Estimate</th>
<th align="right">Naive S.E.</th>
<th align="right">Naive z</th>
<th align="right">Robust S.E.</th>
<th align="right">Robust z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-0.9312798</td>
<td align="right">0.4791852</td>
<td align="right">-1.9434655</td>
<td align="right">0.4612499</td>
<td align="right">-2.0190352</td>
</tr>
<tr class="even">
<td align="left">centre2</td>
<td align="right">0.6727947</td>
<td align="right">0.3390779</td>
<td align="right">1.9841895</td>
<td align="right">0.3548202</td>
<td align="right">1.8961568</td>
</tr>
<tr class="odd">
<td align="left">trttrt</td>
<td align="right">1.2789154</td>
<td align="right">0.3354409</td>
<td align="right">3.8126404</td>
<td align="right">0.3494500</td>
<td align="right">3.6597956</td>
</tr>
<tr class="even">
<td align="left">gendermale</td>
<td align="right">0.0946735</td>
<td align="right">0.4172964</td>
<td align="right">0.2268736</td>
<td align="right">0.4436295</td>
<td align="right">0.2134068</td>
</tr>
<tr class="odd">
<td align="left">baselinegood</td>
<td align="right">1.9346252</td>
<td align="right">0.3428184</td>
<td align="right">5.6432949</td>
<td align="right">0.3480468</td>
<td align="right">5.5585200</td>
</tr>
<tr class="even">
<td align="left">age</td>
<td align="right">-0.0168892</td>
<td align="right">0.0125574</td>
<td align="right">-1.3449620</td>
<td align="right">0.0129054</td>
<td align="right">-1.3086948</td>
</tr>
</tbody>
</table>
<pre class="r"><code>knitr::kable(summary(resp_sub_gee4)$coef, caption = &quot;Summary coeff of GEE binomial AR-M&quot;)</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-8">Table 1: </span>Summary coeff of GEE binomial AR-M</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Estimate</th>
<th align="right">Naive S.E.</th>
<th align="right">Naive z</th>
<th align="right">Robust S.E.</th>
<th align="right">Robust z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-0.9629448</td>
<td align="right">0.4455161</td>
<td align="right">-2.1614142</td>
<td align="right">0.4611607</td>
<td align="right">-2.0880894</td>
</tr>
<tr class="even">
<td align="left">centre2</td>
<td align="right">0.7427015</td>
<td align="right">0.3146448</td>
<td align="right">2.3604438</td>
<td align="right">0.3562300</td>
<td align="right">2.0848932</td>
</tr>
<tr class="odd">
<td align="left">trttrt</td>
<td align="right">1.2472824</td>
<td align="right">0.3112665</td>
<td align="right">4.0071210</td>
<td align="right">0.3518974</td>
<td align="right">3.5444492</td>
</tr>
<tr class="even">
<td align="left">gendermale</td>
<td align="right">0.1132323</td>
<td align="right">0.3883671</td>
<td align="right">0.2915599</td>
<td align="right">0.4494506</td>
<td align="right">0.2519348</td>
</tr>
<tr class="odd">
<td align="left">baselinegood</td>
<td align="right">1.9113953</td>
<td align="right">0.3167921</td>
<td align="right">6.0335952</td>
<td align="right">0.3501873</td>
<td align="right">5.4582088</td>
</tr>
<tr class="even">
<td align="left">age</td>
<td align="right">-0.0169164</td>
<td align="right">0.0116652</td>
<td align="right">-1.4501525</td>
<td align="right">0.0129273</td>
<td align="right">-1.3085816</td>
</tr>
</tbody>
</table>
<p>Looking at the difference between Naive z and Robust z with relevant variables for the above models, resp_sub_gee3 with unstructured comparison correlation structure model tends to have a minimal difference between Naive z and Robust z than others. Therefore, in this case, unstructured model fits best.</p>
<p>Which model is the best? Compare the following models: independent, exchangable, and what ever models we tried previously. Perhaps we can use QIC (in ), MSE, misclassification rate, comparison of naive vs robust Z-score, or another method.</p>
<pre><code>## Fitting GEE Independent</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-9">Table 2: </span>QIC from GGE independent</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">QIC</td>
<td align="right">508.5300</td>
</tr>
<tr class="even">
<td align="left">QICu</td>
<td align="right">495.2182</td>
</tr>
<tr class="odd">
<td align="left">Quasi Lik</td>
<td align="right">-241.6091</td>
</tr>
<tr class="even">
<td align="left">CIC</td>
<td align="right">12.6559</td>
</tr>
<tr class="odd">
<td align="left">params</td>
<td align="right">6.0000</td>
</tr>
<tr class="even">
<td align="left">QICC</td>
<td align="right">508.7222</td>
</tr>
</tbody>
</table>
<pre><code>## Fitting GEE Exchangeable</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-9">Table 2: </span>QIC from GGE exchangeable</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">QIC</td>
<td align="right">495.795035</td>
</tr>
<tr class="even">
<td align="left">QICu</td>
<td align="right">495.218168</td>
</tr>
<tr class="odd">
<td align="left">Quasi Lik</td>
<td align="right">-241.609084</td>
</tr>
<tr class="even">
<td align="left">CIC</td>
<td align="right">6.288434</td>
</tr>
<tr class="odd">
<td align="left">params</td>
<td align="right">6.000000</td>
</tr>
<tr class="even">
<td align="left">QICC</td>
<td align="right">496.051916</td>
</tr>
</tbody>
</table>
<pre><code>## Fitting GEE Unstructured</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-9">Table 2: </span>QIC from GGE Unstructured</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">QIC</td>
<td align="right">495.741778</td>
</tr>
<tr class="even">
<td align="left">QICu</td>
<td align="right">495.336132</td>
</tr>
<tr class="odd">
<td align="left">Quasi Lik</td>
<td align="right">-241.668066</td>
</tr>
<tr class="even">
<td align="left">CIC</td>
<td align="right">6.202823</td>
</tr>
<tr class="odd">
<td align="left">params</td>
<td align="right">6.000000</td>
</tr>
<tr class="even">
<td align="left">QICC</td>
<td align="right">496.465676</td>
</tr>
</tbody>
</table>
<pre><code>## Fitting GEE ar1</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-9">Table 2: </span>QIC from GGE ar1</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">QIC</td>
<td align="right">496.834891</td>
</tr>
<tr class="even">
<td align="left">QICu</td>
<td align="right">495.642425</td>
</tr>
<tr class="odd">
<td align="left">Quasi Lik</td>
<td align="right">-241.821212</td>
</tr>
<tr class="even">
<td align="left">CIC</td>
<td align="right">6.596233</td>
</tr>
<tr class="odd">
<td align="left">params</td>
<td align="right">6.000000</td>
</tr>
<tr class="even">
<td align="left">QICC</td>
<td align="right">497.091771</td>
</tr>
</tbody>
</table>
<p>As mentioned above, <code>resp_sub_gee3</code> with unstructured correlation structure model has slightly minimal difference of Naive z and Robust z than others. We used the QIC value to compare the result, it looks like the third model with unstructured correlation structure model has a lower QIC value of 495.74 than the other three models. So, the model with unstructured correlation structure is the best among four.</p>
<p>Now, we will use the dataset <span class="math inline">\(\textbf{schizophrenia2}\)</span> from <span class="math inline">\(\textbf{HSAUR3}\)</span> package. This was collected in a follow-up study of women patients with schizophrenia (Davis, 2002). The binary response recorded at 0, 2, 6, 8 and 10 months after hospitalization was ``thought disorder’’ (absent or present). The single covariate is the factor indicating whether a patient had suffered early or late onset of her condition (age of onset less than 20 years or age of onset 20 years or above).</p>
<p>The question of interest is whether the course of the illness differs between patients with early and late onset schizophrenia. (<a href="https://www.rdocumentation.org/packages/HSAUR3/versions/1.0-9/topics/schizophrenia2" class="uri">https://www.rdocumentation.org/packages/HSAUR3/versions/1.0-9/topics/schizophrenia2</a>)</p>
<p>We will now investigate this question using plots and summary statistics</p>
<pre><code>## Calculating percentage data</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-10">Table 3: </span>Summary statistics for presence of younger onset data</caption>
<thead>
<tr class="header">
<th align="right">Min.</th>
<th align="right">1st Qu.</th>
<th align="right">Median</th>
<th align="right">Mean</th>
<th align="right">3rd Qu.</th>
<th align="right">Max.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.09375</td>
<td align="right">0.15625</td>
<td align="right">0.25</td>
<td align="right">0.34375</td>
<td align="right">0.59375</td>
<td align="right">0.625</td>
</tr>
</tbody>
</table>
<table>
<caption><span id="tab:unnamed-chunk-10">Table 3: </span>Summary statistics for presence of older onset data</caption>
<thead>
<tr class="header">
<th align="right">Min.</th>
<th align="right">1st Qu.</th>
<th align="right">Median</th>
<th align="right">Mean</th>
<th align="right">3rd Qu.</th>
<th align="right">Max.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="right">0.0833333</td>
<td align="right">0.09375</td>
<td align="right">0.2520833</td>
<td align="right">0.5</td>
<td align="right">0.5833333</td>
</tr>
</tbody>
</table>
<p><img src="/post/Longitudinal_Data_Analysis_and_Mixed_Models/Longitudinal_Data_Analysis_and_Mixed_Models_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>For the older-onset population, the mean and the median of the percentage of’ presence of schizophrenia’ are lower. Looking at the percentage plot, it appears that at each sample date (in months) the percentage is lower in the older-onset population.</p>
<p>Then with the GEE approach:</p>
<table>
<caption><span id="tab:unnamed-chunk-11">Table 4: </span>QIC from GEE Independent (identity)</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">QIC</td>
<td align="right">163.788881</td>
</tr>
<tr class="even">
<td align="left">QICu</td>
<td align="right">159.831542</td>
</tr>
<tr class="odd">
<td align="left">Quasi Lik</td>
<td align="right">-75.915771</td>
</tr>
<tr class="even">
<td align="left">CIC</td>
<td align="right">5.978669</td>
</tr>
<tr class="odd">
<td align="left">params</td>
<td align="right">4.000000</td>
</tr>
<tr class="even">
<td align="left">QICC</td>
<td align="right">164.046945</td>
</tr>
</tbody>
</table>
<table>
<caption><span id="tab:unnamed-chunk-11">Table 4: </span>QIC from GEE Exchangeable</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">QIC</td>
<td align="right">159.800970</td>
</tr>
<tr class="even">
<td align="left">QICu</td>
<td align="right">160.156189</td>
</tr>
<tr class="odd">
<td align="left">Quasi Lik</td>
<td align="right">-76.078094</td>
</tr>
<tr class="even">
<td align="left">CIC</td>
<td align="right">3.822391</td>
</tr>
<tr class="odd">
<td align="left">params</td>
<td align="right">4.000000</td>
</tr>
<tr class="even">
<td align="left">QICC</td>
<td align="right">160.190581</td>
</tr>
</tbody>
</table>
<table>
<caption><span id="tab:unnamed-chunk-11">Table 4: </span>QIC from GEE Unstructured</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">QIC</td>
<td align="right">160.480447</td>
</tr>
<tr class="even">
<td align="left">QICu</td>
<td align="right">160.652702</td>
</tr>
<tr class="odd">
<td align="left">Quasi Lik</td>
<td align="right">-76.326351</td>
</tr>
<tr class="even">
<td align="left">CIC</td>
<td align="right">3.913873</td>
</tr>
<tr class="odd">
<td align="left">params</td>
<td align="right">4.000000</td>
</tr>
<tr class="even">
<td align="left">QICC</td>
<td align="right">161.956957</td>
</tr>
</tbody>
</table>
<p>In exchangeable and unstructured model, the QIC score is the lowest. So for the selection of model, either model can be a good choice. However, comparing parameters such as CIC, QICu and QICC, I think the exchangeable model seems better.</p>
<p>Then with the mixed effects model (lmer):</p>
<pre><code>## [1] &quot;Without interaction term:&quot;</code></pre>
<pre><code>## [1] &quot;BIC: Fixed Slope :  179.591302394191&quot;</code></pre>
<pre><code>## [1] &quot;BIC: Random Slope:  184.624562858509&quot;</code></pre>
<pre><code>## [1] &quot;With interaction term: month v. onset:&quot;</code></pre>
<pre><code>## [1] &quot;BIC: Fixed Slope :  184.587333241198&quot;</code></pre>
<pre><code>## [1] &quot;BIC: Random Slope:  189.62089162902&quot;</code></pre>
<p>Here, we will try to see if there is a difference between the models and what model(s) work the best. We will do model comparison with ANOVA:</p>
<pre><code>## Fixed Slope v. Random Slope (no intaction term)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">npar</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">logLik</th>
<th align="right">deviance</th>
<th align="right">Chisq</th>
<th align="right">Df</th>
<th align="right">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">schiz_lmer1</td>
<td align="right">6</td>
<td align="right">161.1403</td>
<td align="right">179.5913</td>
<td align="right">-74.57013</td>
<td align="right">149.1403</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">schiz_lmer2</td>
<td align="right">8</td>
<td align="right">160.0232</td>
<td align="right">184.6246</td>
<td align="right">-72.01159</td>
<td align="right">144.0232</td>
<td align="right">5.117087</td>
<td align="right">2</td>
<td align="right">0.0774174</td>
</tr>
</tbody>
</table>
<pre><code>## Interaction Term v. No Interaction Term (fixed slope)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">npar</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">logLik</th>
<th align="right">deviance</th>
<th align="right">Chisq</th>
<th align="right">Df</th>
<th align="right">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">schiz_lmer1</td>
<td align="right">6</td>
<td align="right">161.1403</td>
<td align="right">179.5913</td>
<td align="right">-74.57013</td>
<td align="right">149.1403</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">schiz_lmer3</td>
<td align="right">7</td>
<td align="right">163.0611</td>
<td align="right">184.5873</td>
<td align="right">-74.53056</td>
<td align="right">149.0611</td>
<td align="right">0.079143</td>
<td align="right">1</td>
<td align="right">0.7784622</td>
</tr>
</tbody>
</table>
<pre><code>## Fixed Slope, No interaction Term v. Random Slope, With interaction term</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">npar</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">logLik</th>
<th align="right">deviance</th>
<th align="right">Chisq</th>
<th align="right">Df</th>
<th align="right">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">schiz_lmer1</td>
<td align="right">6</td>
<td align="right">161.1403</td>
<td align="right">179.5913</td>
<td align="right">-74.57013</td>
<td align="right">149.1403</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">schiz_lmer4</td>
<td align="right">9</td>
<td align="right">161.9443</td>
<td align="right">189.6209</td>
<td align="right">-71.97216</td>
<td align="right">143.9443</td>
<td align="right">5.195932</td>
<td align="right">3</td>
<td align="right">0.1579995</td>
</tr>
</tbody>
</table>
<pre><code>## Random Slope, No interaction term v. Fixed Slope, With interaction term</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">npar</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">logLik</th>
<th align="right">deviance</th>
<th align="right">Chisq</th>
<th align="right">Df</th>
<th align="right">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">schiz_lmer3</td>
<td align="right">7</td>
<td align="right">163.0611</td>
<td align="right">184.5873</td>
<td align="right">-74.53056</td>
<td align="right">149.0611</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">schiz_lmer2</td>
<td align="right">8</td>
<td align="right">160.0232</td>
<td align="right">184.6246</td>
<td align="right">-72.01159</td>
<td align="right">144.0232</td>
<td align="right">5.037944</td>
<td align="right">1</td>
<td align="right">0.0247979</td>
</tr>
</tbody>
</table>
<pre><code>## No interaction term v. Interaction term (random slope)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">npar</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">logLik</th>
<th align="right">deviance</th>
<th align="right">Chisq</th>
<th align="right">Df</th>
<th align="right">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">schiz_lmer2</td>
<td align="right">8</td>
<td align="right">160.0232</td>
<td align="right">184.6246</td>
<td align="right">-72.01159</td>
<td align="right">144.0232</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">schiz_lmer4</td>
<td align="right">9</td>
<td align="right">161.9443</td>
<td align="right">189.6209</td>
<td align="right">-71.97216</td>
<td align="right">143.9443</td>
<td align="right">0.078845</td>
<td align="right">1</td>
<td align="right">0.7788687</td>
</tr>
</tbody>
</table>
<pre><code>## Fixed Slope v. Random Slope (with intaction term)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">npar</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">logLik</th>
<th align="right">deviance</th>
<th align="right">Chisq</th>
<th align="right">Df</th>
<th align="right">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">schiz_lmer3</td>
<td align="right">7</td>
<td align="right">163.0611</td>
<td align="right">184.5873</td>
<td align="right">-74.53056</td>
<td align="right">149.0611</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">schiz_lmer4</td>
<td align="right">9</td>
<td align="right">161.9443</td>
<td align="right">189.6209</td>
<td align="right">-71.97216</td>
<td align="right">143.9443</td>
<td align="right">5.116789</td>
<td align="right">2</td>
<td align="right">0.0774289</td>
</tr>
</tbody>
</table>
<p>The model with a fixed effect and no interaction term has the lowest BIC score. This would be an indicator that the concept of contact is not likely to add much to the template if anything. The most significant difference based on ANOVA analysis is between random slope, no interaction term and fixed slope, with interaction term (fourth table). This is indicated with a p-score of 0.025 i.e., [P&lt;0.05].</p>
</div>
